### PR TITLE
Initial support for Aptabase.MAUI reliable delivery via persistent channel

### PR DESCRIPTION
**Pull request by TTalpey**
Aptabase.MAUI.csproj:
- Add Dotnext.Threading for persistent channel
- Set iOS minimum platform to 11.0 to match MAUI
- .Net SDK to net8 (dotnext.threading requires it, also net7 no longer in support)

AptabaseOptions.cs:
- Add IsPersistent option to request new behavior

AptabaseClient.cs:
- Implementation

### CODE REVIEW

**Comment by cristipufu** [comment]
@TTalpey thanks for your contributions, looks good 🙏 

I will properly review it in the next few days

**Comment by TTalpey** [comment]
I found an issue in testing under load, the JsonDeserializer was throwing when the eventdata channel backs up. The processing task now feeds it only one entry at a time.

**Review by cristipufu — APPROVED** [review]
Looks good to me 👍 

We can merge it if it's ready

**Comment by TTalpey** [comment]
Thanks!! No new issues testing over the weekend. I'll click the "ready" button and leave it to you.

**Pull request merged**
